#!/usr/bin/sh
export src=./src/com/example/helloandroid/*.java
export api=./src/com/example/helloandroid/android.jar
export java=./jre/bin/
export PROJ=./
./java/bin/javac -d ./obj/ $src
aapt package -f -m -J $PROJ/src -M $PROJ/AndroidManifest.xml -S $PROJ/res -I $api
dx --dex --output=$PROJ/bin/classes.dex $PROJ/obj
aapt package -f -m -F $PROJ/bin/hello.unaligned.apk -M $PROJ/AndroidManifest.xml -S $PROJ/res -I $api
cp $PROJ/bin/classes.dex .
aapt add $PROJ/bin/hello.unaligned.apk classes.dex
zipalign -f 4 $PROJ/bin/hello.unaligned.apk $PROJ/bin/hello.apk
keytool -genkeypair -validity 1 -keystore mykey.keystore -keyalg RSA -keysize 2048
apksigner sign --ks mykey.keystore $PROJ/bin/hello.apk
rm ./classes.dex
rm -r ./obj/com
rm ./bin/classes.dex
rm ./mykey.keystore
